### PR TITLE
Pradhvan Bisht

### PR DESCRIPTION
**Pull request by Pradhvan**
- [x] file interns.md, format Name [\github-username\]\(github-username-url\)
- [x] Name as heading
- [ ] Description should have
     - [x] Name
     - [x] Mail id
     - [ ] Tickets closed
     - [ ] PRs created
     - [x] Timezone
     - [x] Independent side projects work/writeup
     - [ ] Timeline doc
     - [ ] Channel availability (Calendly url)
     - [ ] Daily meeting preffered timing (Calendly url)

### CODE REVIEW

**Review by tapaswenipathak — COMMENTED** [review]
Heyo! Please complete the description for formality and write independent side projects.

**Comment by Pradhvan** [comment]
@tapaswenipathak  Hey ! is there a timeline to close the initial 9 issues?

**Comment by tapaswenipathak** [comment]
On Sun, Jun 16, 2019 at 10:25 PM Pradhvan Bisht
<notifications@github.com> wrote:
>
> @tapaswenipathak Hey ! is there a timeline for closing the initial 9 issues?

I just dropped you a mail.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Tapasweni

**Comment by Pradhvan** [comment]
> On Sun, Jun 16, 2019 at 10:25 PM Pradhvan Bisht ***@***.***> wrote: @tapaswenipathak Hey ! is there a timeline for closing the initial 9 issues?
> I just dropped you a mail.
> […](#)
> — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
> -- Tapasweni

okay :smile:  Will reply as soon as I get it.

**Pull request closed without merging**
